=== Oyuanchu/HoshinoBot-plugins-index/.ci/plugin-schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "HoshinoBot Plugin Information Schema",
	"description": "Schema for HoshinoBot plugin information",
	"type": "object",
	"required": ["name", "link", "authors"],
	"properties": {
		"name": {
			"type": "string",
			"description": "The name of the plugin",
			"minLength": 1,
			"maxLength": 100
		},
		"description": {
			"type": "string",
			"description": "A brief description of what the plugin does",
			"minLength": 0,
			"maxLength": 500
		},
		"link": {
			"type": "string",
			"description": "The repository or homepage URL of the plugin",
			"format": "uri",
			"pattern": "^https?://"
		},
		"authors": {
			"type": "array",
			"description": "List of plugin authors",
			"minItems": 1,
			"items": {
				"type": "object",
				"required": ["name"],
				"properties": {
					"name": {
						"type": "string",
						"description": "Author's name or username",
						"minLength": 1,
						"maxLength": 50
					},
					"link": {
						"type": "string",
						"description": "Author's profile or homepage URL",
						"format": "uri",
						"pattern": "^https?://"
					}
				},
				"additionalProperties": false
			}
		},
		"last_updated": {
			"type": "integer",
			"description": "Unix timestamp of when the plugin was last updated",
			"minimum": 0
		},
		"stars": {
			"type": "integer",
			"description": "Number of stars the plugin has received",
			"minimum": 0
		}
	},
	"additionalProperties": false
}

=== Oyuanchu/HoshinoBot-plugins-index/plugins/SlightDust/HuoZiYinShua_HoshinoBot.json
{
	"name": "otto活字印刷",
	"link": "https://github.com/SlightDust/HuoZiYinShua_HoshinoBot",
	"authors": [
		{
			"name": "@SlightDust",
			"link": "https://github.com/SlightDust/"
		}
	],
	"description": "电棍活字印刷，基于[DSP-8192/HuoZiYinShua](https://github.com/DSP-8192/HuoZiYinShua)，参考了[Kazagumo/nonebot-HuoZiYinShua](https://github.com/Kazagumo/nonebot-HuoZiYinShua)",
	"last_updated": 1727843659,
	"stars": 2
}

=== Oyuanchu/HoshinoBot-plugins-index/plugins/SonderXiaoming/homo.json
{
	"name": "数字恶臭化插件",
	"link": "https://github.com/SonderXiaoming/homo",
	"authors": [
		{
			"name": "@SonderXiaoming",
			"link": "https://github.com/SonderXiaoming"
		},
		{
			"name": "@stbcx001",
			"link": "https://github.com/stbcx001"
		}
	],
	"description": "将任意数字以114514表示",
	"last_updated": 1747756469,
	"stars": 6
}

=== Oyuanchu/HoshinoBot-plugins-index/plugins/C-Jun-GIT/Oreo.json
{
	"name": "奥利奥绘制",
	"link": "https://github.com/C-Jun-GIT/Oreo",
	"authors": [
		{
			"name": "@菌落",
			"link": "https://github.com/C-Jun-GIT/Oreo"
		},
		{
			"name": "@咕咕鸽",
			"link": "https://github.com/Adminicoder"
		}
	],
	"description": "通过排列组合来自定义属于自己的奥利奥吧！",
	"last_updated": 1645858475,
	"stars": 4
}

=== Oyuanchu/HoshinoBot-plugins-index/plugins/azmiao/pcrjjc3-tw.json
{
	"name": "pcrjjc3",
	"link": "https://github.com/azmiao/pcrjjc3-tw",
	"authors": [
		{
			"name": "@cc004",
			"link": "https://github.com/cc004"
		},
		{
			"name": "@azmiao",
			"link": "https://github.com/azmiao"
		},
		{
			"name": "@CYDXDianXian",
			"link": "https://github.com/CYDXDianXian"
		}
	],
	"description": "由pcrjjc2修改而来的适用pcr台服的竞技场插件，额外支持了多服查询",
	"last_updated": 1747307544,
	"stars": 17
}

=== Oyuanchu/HoshinoBot-plugins-index/plugins/SlightDust/steam_HoshinoBot.json
{
	"name": "steam群友游戏状态播报",
	"link": "https://github.com/SlightDust/steam_HoshinoBot",
	"authors": [
		{
			"name": "@SlightDust",
			"link": "https://github.com/SlightDust"
		},
		{
			"name": "@GaryDu0123",
			"link": "https://github.com/GaryDu0123"
		}
	],
	"description": "[pcrbot/steam](https://github.com/pcrbot/steam)的fork。原项目停更很久了，fork来缝了一下",
	"last_updated": 1747619849,
	"stars": 4
}

=== Oyuanchu/HoshinoBot-plugins-index/plugins/haha114514/tarot_hoshino.json
{
	"name": "Tarot",
	"link": "https://github.com/haha114514/tarot_hoshino",
	"authors": [
		{
			"name": "@haha114514",
			"link": "https://github.com/haha114514"
		},
		{
			"name": "@realhyy",
			"link": "https://github.com/realhyy"
		}
	],
	"description": "修改为Hoshinobot版：[@haha114514](https://github.com/haha114514)   源代码：[@realhyy](https://github.com/realhyy) 适用于HoshinoBot的哔哩哔哩主题塔罗牌抽签（灵感来自于https://github.com/loli-fish/destiny_tarrot-CQnonebot ）",
	"last_updated": 1666964852,
	"stars": 17
}

=== Oyuanchu/HoshinoBot-plugins-index/plugins/watermellye/yaowoyizhi.json
{
	"name": "图片套娃",
	"link": "https://github.com/watermellye/yaowoyizhi/",
	"authors": [
		{
			"name": "@ellye",
			"link": "https://github.com/watermellye"
		},
		{
			"name": "@mahosho",
			"link": "https://github.com/mahosho"
		}
	],
	"description": "[要我一直img吗](https://github.com/pcrbot/yaowoyizhi)重构版，新增套娃和支持自定义文字。",
	"last_updated": 1659335819,
	"stars": 3
}

=== Oyuanchu/HoshinoBot-plugins-index/plugins/Zoe-Wh1t3zZ/Switch.json
{
	"name": "全局开关",
	"link": "https://github.com/Zoe-Wh1t3zZ/Switch/",
	"authors": [
		{
			"name": "@Zoe新小白白白",
			"link": "https://github.com/Zoe-Wh1t3zZ/"
		},
		{
			"name": "@Jaco",
			"link": "https://github.com/Jacosnow/"
		}
	],
	"description": "基于hoshino的(伪)全局开关，通过拉黑群实现休眠。",
	"last_updated": 1648132980,
	"stars": 0
}
