=== Oyuanchu/HoshinoBot-plugins-index/.ci/plugin-schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "HoshinoBot Plugin Information Schema",
	"description": "Schema for HoshinoBot plugin information",
	"type": "object",
	"required": ["name", "link", "authors"],
	"properties": {
		"name": {
			"type": "string",
			"description": "The name of the plugin",
			"minLength": 1,
			"maxLength": 100
		},
		"description": {
			"type": "string",
			"description": "A brief description of what the plugin does",
			"minLength": 0,
			"maxLength": 500
		},
		"link": {
			"type": "string",
			"description": "The repository or homepage URL of the plugin",
			"format": "uri",
			"pattern": "^https?://"
		},
		"authors": {
			"type": "array",
			"description": "List of plugin authors",
			"minItems": 1,
			"items": {
				"type": "object",
				"required": ["name"],
				"properties": {
					"name": {
						"type": "string",
						"description": "Author's name or username",
						"minLength": 1,
						"maxLength": 50
					},
					"link": {
						"type": "string",
						"description": "Author's profile or homepage URL",
						"format": "uri",
						"pattern": "^https?://"
					}
				},
				"additionalProperties": false
			}
		},
		"last_updated": {
			"type": "integer",
			"description": "Unix timestamp of when the plugin was last updated",
			"minimum": 0
		},
		"stars": {
			"type": "integer",
			"description": "Number of stars the plugin has received",
			"minimum": 0
		}
	},
	"additionalProperties": false
}

=== Oyuanchu/HoshinoBot-plugins-index/plugins/CYDXDianXian/chat_count.json
{
	"name": "群聊关键消息记录",
	"link": "https://github.com/CYDXDianXian/chat_count",
	"authors": [
		{
			"name": "@CYDXDianXian",
			"link": "https://github.com/CYDXDianXian"
		}
	],
	"description": "该插件可记录群聊中某关键字的触发次数、时间、与完整消息，并可对储存记录的消息方便的进行读取，以查看群友们都围绕该关键字说了什么",
	"last_updated": 1680107024,
	"stars": 7
}

=== Oyuanchu/HoshinoBot-plugins-index/plugins/azmiao/PalWorldPlugin.json
{
	"name": "幻兽帕鲁插件",
	"link": "https://github.com/azmiao/PalWorldPlugin",
	"authors": [
		{
			"name": "@azmiao",
			"link": "https://github.com/azmiao"
		},
		{
			"name": "@SlightDust",
			"link": "https://github.com/SlightDust"
		},
		{
			"name": "@Lancercmd",
			"link": "https://github.com/Lancercmd"
		}
	],
	"description": "一个帕鲁的QQ机器人插件",
	"last_updated": 1719910033,
	"stars": 10
}

=== Oyuanchu/HoshinoBot-plugins-index/plugins/chingkingm/Hoshinobot-plugin-petpet.json
{
	"name": "Hoshinobot-plugin-petpet",
	"link": "https://github.com/chingkingm/Hoshinobot-plugin-petpet",
	"authors": [
		{
			"name": "@MeetWq",
			"link": "https://github.com/MeetWq"
		},
		{
			"name": "@chingkingm",
			"link": "https://github.com/chingkingm"
		}
	],
	"description": "移植自[nonebot-plugin-petpet](https://github.com/MeetWq/nonebot-plugin-petpet)的头像表情包生成器",
	"last_updated": 1655818707,
	"stars": 20
}

=== Oyuanchu/HoshinoBot-plugins-index/plugins/joeyHXD/dota2_watcher_bot.json
{
	"name": "DOTA2战绩推送",
	"link": "https://github.com/joeyHXD/dota2_watcher_bot",
	"authors": [
		{
			"name": "@joeyHXD",
			"link": "https://github.com/joeyHXD"
		}
	],
	"description": "基于[CSGO和DOTA2的处刑BOT](https://github.com/greenhaha/dota2_csgo_watcher_bot)魔改而来的DOTA2战绩推送插件",
	"last_updated": 1724861315,
	"stars": 10
}

=== Oyuanchu/HoshinoBot-plugins-index/plugins/azmiao/authMS_lite.json
{
	"name": "授权管理精简版",
	"link": "https://github.com/azmiao/authMS_lite",
	"authors": [
		{
			"name": "@azmiao",
			"link": "https://github.com/azmiao"
		}
	],
	"description": "[授权管理](https://github.com/pcrbot/authMS)的自用精简版\n适配v1.0.0+的go-cqhttp\n其他各种精简和优化修改",
	"last_updated": 1698199237,
	"stars": 1
}

=== Oyuanchu/HoshinoBot-plugins-index/plugins/azmiao/pcrjjc_tw_new.json
{
	"name": "新版台服竞技场查询",
	"link": "https://github.com/azmiao/pcrjjc_tw_new",
	"authors": [
		{
			"name": "@azmiao",
			"link": "https://github.com/azmiao"
		}
	],
	"description": "由[pcrjjc3](https://github.com/azmiao/pcrjjc3-tw)修改而来\n兼容[2佬](https://github.com/sdyxxjj123)和[辣鱼佬](https://github.com/layvsan)的适配方法\n并增加全局禁用推送功能和各种优化",
	"last_updated": 1748997938,
	"stars": 9
}

=== Oyuanchu/HoshinoBot-plugins-index/plugins/SonderXiaoming/money_exchange_rate.json
{
	"name": "汇率查询",
	"link": "https://github.com/SonderXiaoming/money_exchange_rate",
	"authors": [
		{
			"name": "@SonderXiaoming",
			"link": "https://github.com/SonderXiaoming"
		},
		{
			"name": "@stbcx001",
			"link": "https://github.com/stbcx001"
		}
	],
	"description": "查询货币汇率，支持自定义",
	"last_updated": 1678425397,
	"stars": 4
}

=== Oyuanchu/HoshinoBot-plugins-index/plugins/GaryDu0123/SetuScore.json
{
	"name": "色图评分fork版",
	"link": "https://github.com/GaryDu0123/SetuScore",
	"authors": [
		{
			"name": "@GaryDu0123",
			"link": "https://github.com/GaryDu0123"
		}
	],
	"description": "对[原仓库](https://github.com/pcrbot/SetuScore)进行了修改, 保持色图评分的常态开启, 评分高于一定值才会进行提示, 添加了可调整的阈值禁言",
	"last_updated": 1728527189,
	"stars": 1
}
